// -------------------------------------------------------------------------------
// 
// 		‚c‚wƒ‰ƒCƒuƒ‰ƒŠ		‚c‚‰‚’‚…‚ƒ‚”‚wŽü‚è‚Ì‚f‚t‚h‚c’è‹`ƒwƒbƒ_ƒtƒ@ƒCƒ‹
// 
// 				Ver 3.16d
// 
// -------------------------------------------------------------------------------

#ifndef __DXGUID__
#define __DXGUID__

#include "../DxCompileConfig.h"
#include <windows.h>

#ifndef DX_NON_NAMESPACE

namespace DxLib
{

#endif // DX_NON_NAMESPACE

extern GUID IID_IUNKNOWN ;
extern GUID IID_ISTREAM ;
extern GUID _GUID_NULL ;
extern GUID IID_IDIRECT3DHALDEVICE ;
extern GUID IID_IDIRECT3DTNLHALDEVICE  ;
extern GUID IID_IDIRECT3D7 ;
extern GUID IID_IDIRECT3DTEXTURE9 ;
extern GUID IID_IDXGIDEVICE1 ;
extern GUID IID_IDXGIFACTORY ;
extern GUID IID_IDXGIFACTORY1 ;
extern GUID IID_ID3D11TEXTURE2D ;

extern GUID CLSID_DIRECTDRAW7 ;
extern GUID IID_IDIRECTDRAWSURFACE3 ;
extern GUID IID_IDIRECTDRAWSURFACE4 ;
extern GUID IID_IDIRECTDRAWSURFACE7 ;
extern GUID IID_IDIRECTDRAW ;
extern GUID IID_IDIRECTDRAW2 ;
extern GUID IID_IDIRECTDRAW4 ;
extern GUID IID_IDIRECTDRAW7 ;

extern GUID CLSID_FILTERGRAPH ;
extern GUID CLSID_FILTERMAPPER ;
extern GUID CLSID_AMMULTIMEDIASTREAM ;
extern GUID CLSID_VIDEOMIXINGRENDERER9 ;
extern GUID CLSID_MEMORYALLOCATOR ;
extern GUID CLSID_FILEWRITER ;
extern GUID CLSID_NULLRENDERER ;
extern GUID CLSID_WAVDEST ;
extern GUID IID_IMEMALLOCATOR ;
extern GUID IID_IMEMALLOCATORCALLBACKTEMP ;
extern GUID IID_IMEDIASAMPLE ;
extern GUID IID_IMEDIASAMPLE2 ;
extern GUID IID_IPIN ;
extern GUID CLSID_SAMPLEGRABBER ;
extern GUID CLSID_SEEKINGPASSTHRU ;
extern GUID CLSID_GRABBERSAMPLE ;
extern GUID IID_IGRABBERSAMPLE ;
extern GUID IID_ISEEKINGPASSTHRU ;
extern GUID IID_ISAMPLEGRABBER ;
extern GUID IID_FILESINKFILTER ;
extern GUID IID_FILESINKFILTER2 ;
extern GUID IID_IASYNCREADER ;

#define D_MEDIATYPE_NULL				_GUID_NULL
#define D_MEDIASUBTYPE_NULL				_GUID_NULL

extern GUID IID_IENUMMEDIATYPES ;
extern GUID IID_IENUMPINS ;
extern GUID IID_IAMOVIESETUP ;
extern GUID IID_IBASICAUDIO ;
extern GUID IID_IMEDIASEEKING ;
extern GUID IID_IMEDIAEVENT ;
extern GUID IID_IMEDIAEVENTEX ;
extern GUID IID_IMEDIACONTROL ;
extern GUID IID_IMEDIAPOSITION ;
extern GUID IID_IMEDIAEVENTSINK ;
extern GUID IID_IQUALITYCONTROL ;
extern GUID IID_IQUALPROP ;
extern GUID IID_IMEDIAFILTER ;
extern GUID IID_IPERSIST ;
extern GUID IID_IGRAPHBUILDER ;
extern GUID IID_IDIRECTDRAWMEDIASTREAM ;
extern GUID IID_IAMMEDIASTREAM ;
extern GUID IID_IAMMULTIMEDIASTREAM ;
extern GUID IID_IFILTERGRAPH ;
extern GUID IID_IFILTERGRAPH2 ;
extern GUID IID_IFILTERMAPPER ;
extern GUID LIBID_QUARTZTYPELIB ;
extern GUID IID_IMEMINPUTPIN ;
extern GUID IID_ISAMPLEGRABBERCB ;
extern GUID MSPID_PRIMARYAUDIO ;
extern GUID MSPID_PRIMARYVIDEO ;

extern GUID IID_IBASEFILTER ;
extern GUID IID_IVMRSURFACEALLOCATOR9 ;
extern GUID IID_IVMRSURFACEALLOCATORNOTIFY9 ;
extern GUID IID_IVMRIMAGEPRESENTER9 ;
extern GUID IID_IVMRFILTERCONFIG9 ;
extern GUID IID_IREFERENCECLOCK ;

extern GUID FORMAT_VIDEOINFO ;
extern GUID FORMAT_WAVEFORMATEX ;
extern GUID MEDIATYPE_VIDEO ;
extern GUID MEDIATYPE_AUDIO ;
extern GUID MEDIATYPE_STREAM ;
extern GUID D_MEDIASUBTYPE_YVYU ;
extern GUID D_MEDIASUBTYPE_YUYV ;
extern GUID D_MEDIASUBTYPE_UYVY ;
extern GUID D_MEDIASUBTYPE_YV12 ;
extern GUID D_MEDIASUBTYPE_NV11 ;
extern GUID D_MEDIASUBTYPE_NV12 ;
extern GUID D_MEDIASUBTYPE_YUY2 ;
extern GUID D_MEDIASUBTYPE_RGB24 ;
extern GUID D_MEDIASUBTYPE_RGB32 ;
extern GUID D_MEDIASUBTYPE_PCM ;
extern GUID D_MEDIASUBTYPE_WAVE ;
extern GUID D_MEDIASUBTYPE_MPEG1SYSTEM ;
extern GUID D_MEDIASUBTYPE_MPEG1AUDIO ;
extern GUID D_MEDIASUBTYPE_MPEG1VIDEO ;
extern GUID D_MEDIASUBTYPE_MPEG1VIDEOCD ;
extern GUID D_MEDIASUBTYPE_AVI ;
extern GUID D_MEDIASUBTYPE_QTMOVIE ;

extern GUID D_TIME_FORMAT_NONE ;
extern GUID D_TIME_FORMAT_FRAME ;
extern GUID D_TIME_FORMAT_BYTE ;
extern GUID D_TIME_FORMAT_SAMPLE ;
extern GUID D_TIME_FORMAT_FIELD ;
extern GUID D_TIME_FORMAT_MEDIA_TIME ;

extern GUID CLSID_DIRECTINPUT ;
extern GUID CLSID_DIRECTINPUT_ ;
extern GUID CLSID_DIRECTINPUT8 ;
extern GUID GUID_SYSKEYBOARD ;
extern GUID GUID_SYSMOUSE ;
extern GUID GUID_SINE ;
extern GUID GUID_CONSTANTFORCE ;
//#ifdef UNICODE
extern GUID IID_IDIRECTINPUTDEVICE8 ; // W
extern GUID IID_IDIRECTINPUTDEVICE7 ; // W
extern GUID IID_IDIRECTINPUTDEVICE2 ;
extern GUID IID_IDIRECTINPUTDEVICE ;
extern GUID IID_IDIRECTINPUT8 ;
extern GUID IID_IDIRECTINPUT7 ;
extern GUID IID_IDIRECTINPUT2 ;
extern GUID IID_IDIRECTINPUT ;
//#else
//extern GUID IID_IDIRECTINPUTDEVICE8 ; // A
//extern GUID IID_IDIRECTINPUTDEVICE7 ; // A
//extern GUID IID_IDIRECTINPUTDEVICE2 ;
//extern GUID IID_IDIRECTINPUTDEVICE ;
//extern GUID IID_IDIRECTINPUT8 ;
//extern GUID IID_IDIRECTINPUT7 ;
//extern GUID IID_IDIRECTINPUT2 ;
//extern GUID IID_IDIRECTINPUT ;
//#endif

extern GUID IID_IMMDEVICEENUMERATOR ;
extern GUID CLSID_MMDEVICEENUMERATOR ;

extern GUID GUID_PERFMASTERVOLUME ;
extern GUID GUID_STANDARDMIDIFILE ;
extern GUID GUID_DIRECTMUSICALLTYPES ;
extern GUID CLSID_DIRECTSOUND ;
extern GUID CLSID_DIRECTMUSIC ;
extern GUID CLSID_DIRECTMUSICPERFORMANCE ;
extern GUID CLSID_DIRECTMUSICLOADER ;
extern GUID CLSID_DIRECTMUSICSEGMENT ;
extern GUID IID_IDIRECTSOUND ;
extern GUID IID_IDIRECTSOUNDBUFFER8 ;
extern GUID IID_IDIRECTMUSIC ;
extern GUID IID_IDIRECTMUSICLOADER8 ;
extern GUID IID_IDIRECTMUSICPERFORMANCE8 ;
extern GUID IID_IDIRECTMUSIC8 ;
extern GUID IID_IDIRECTMUSICSEGMENT8 ;

extern GUID CLSID_XAUDIO2_0 ;
extern GUID CLSID_XAUDIO2_0_DEBUG ;
extern GUID CLSID_XAUDIO2_1 ;
extern GUID CLSID_XAUDIO2_1_DEBUG ;
extern GUID CLSID_XAUDIO2_2 ;
extern GUID CLSID_XAUDIO2_2_DEBUG ;
extern GUID CLSID_XAUDIO2_3 ;
extern GUID CLSID_XAUDIO2_3_DEBUG ;
extern GUID CLSID_XAUDIO2_4 ;
extern GUID CLSID_XAUDIO2_4_DEBUG ;
extern GUID CLSID_XAUDIO2_5 ;
extern GUID CLSID_XAUDIO2_5_DEBUG ;
extern GUID CLSID_XAUDIO2_6 ;
extern GUID CLSID_XAUDIO2_6_DEBUG ;
extern GUID CLSID_XAUDIO2_7 ;
extern GUID CLSID_XAUDIO2_7_DEBUG ;
extern GUID IID_IXAUDIO2 ;

extern GUID CLSID_AUDIOVOLUMEMeter2_0 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_0_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_0 ;
extern GUID CLSID_AUDIOREVERB2_0_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_1 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_1_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_1 ;
extern GUID CLSID_AUDIOREVERB2_1_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_2 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_2_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_2 ;
extern GUID CLSID_AUDIOREVERB2_2_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_3 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_3_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_3 ;
extern GUID CLSID_AUDIOREVERB2_3_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_4 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_4_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_4 ;
extern GUID CLSID_AUDIOREVERB2_4_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_5 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_5_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_5 ;
extern GUID CLSID_AUDIOREVERB2_5_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_6 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_6_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_6 ;
extern GUID CLSID_AUDIOREVERB2_6_DEBUG ;
extern GUID CLSID_AUDIOVOLUMEMeter2_7 ;
extern GUID CLSID_AUDIOVOLUMEMeter2_7_DEBUG ;
extern GUID CLSID_AUDIOREVERB2_7 ;
extern GUID CLSID_AUDIOREVERB2_7_DEBUG ;

#ifndef DX_NON_NAMESPACE

}

#endif // DX_NON_NAMESPACE

#endif
